export const queryKeys = {
  about: ["about-section"],
  navbar: ["navbar"],
  bmiSection: ["bmi"],
  finalCTA: ["final-cta"],
  footer: ["footer"],
  hero: ["hero"],
  locations: ["locations"],
  locationSection: ["locations-section"],
  testimonials: ["testimonials"],
  testimonialSection: ["testimonial-section"],
  trainingProgramSection: ["training-program-section"],
  whyChooseUs: ["why-choose-us"],
  bmiCategories: ["bmi-categories"],
  supplements: ["supplements"],
  packages: ["packages"],
  packageSection: ["package-sections"],
  programs: ["program"],
  features: ["features"],
};
